# Generated by Django 2.2.4 on 2020-03-28 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('DOB', models.DateField()),
                ('Bio', models.CharField(max_length=800)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('Date_of_release', models.DateField()),
                ('cover', models.ImageField(upload_to='song_covers')),
                ('artist', models.ManyToManyField(to='music.Artist')),
            ],
        ),
    ]
